"""Add test_value field to TestPrimary again

Revision ID: 6b8b8c476ca5
Revises: bb9a17f74453
Create Date: 2024-10-19 15:05:49.366547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8b8c476ca5'
down_revision: Union[str, None] = 'bb9a17f74453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests_primary', sa.Column('test_value', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests_primary', 'test_value')
    # ### end Alembic commands ###
