"""create migrations

Revision ID: 6dc0987e5a7c
Revises: 
Create Date: 2024-10-19 12:40:16.082467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dc0987e5a7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('core_software',
    sa.Column('pin', sa.String(length=4), nullable=False),
    sa.Column('reset_pin', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('reset_pin')
    )
    op.create_table('operator_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure', sa.String(length=50), nullable=True),
    sa.Column('business', sa.String(length=50), nullable=True),
    sa.Column('collation', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=60), nullable=True),
    sa.Column('selected_printer', sa.String(length=50), nullable=True),
    sa.Column('com', sa.String(length=15), nullable=True),
    sa.Column('test2', sa.Boolean(), nullable=True),
    sa.Column('test3', sa.Boolean(), nullable=True),
    sa.Column('test4', sa.Boolean(), nullable=True),
    sa.Column('test5', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operator_settings')
    op.drop_table('core_software')
    # ### end Alembic commands ###
