"""Add test_value field to TestPrimary

Revision ID: 6e6d2a48cc95
Revises: 2096f3ce29b0
Create Date: 2024-10-19 15:02:35.810297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6d2a48cc95'
down_revision: Union[str, None] = '2096f3ce29b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
