"""Remove test_value field from TestPrimary again

Revision ID: a59cef44fbc7
Revises: 6b8b8c476ca5
Create Date: 2024-10-19 15:09:46.966462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a59cef44fbc7'
down_revision: Union[str, None] = '6b8b8c476ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tests_primary', 'test_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tests_primary', sa.Column('test_value', sa.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
